"$schema" = 'https://starship.rs/config-schema.json'

# prompt for multi-line editor
continuation_prompt = ":: "

[battery]
disabled = true

[directory]
truncation_length = 10
truncate_to_repo = false
